services:
- type: web
  name: historical-agent-bot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  envVars:
    - key: GMAIL_USER
      sync: false
    - key: GMAIL_APP_PASSWORD
      sync: false
